### ISSUE TITLE
Is it possible at all to add vibrancy to an individual HTML element and not the entire window?

### ISSUE THREAD

**Issue by chen-rn** [amrbashir/tauri-plugin-vibrancy#103]
Hey all! I understand this plugin is specifically designed for adding vibrancy to the window, so apologies in advance if this isn't the perfect place.

In my case, ideally I'd want the 2 highlighted elements to have vibrancy, and not the background window.
![Screenshot 2023-09-18 at 2 50 58 PM](https://github.com/tauri-apps/window-vibrancy/assets/36214945/7cbde53f-e4d3-49e3-8dd3-7acd032d8e83)

As of right now, the only way that I can think of to achieve that effect is to create those 2 elements as individual windows. However, that _would_ add some additional positioning and animation work.

I'm not too familiar with the native window APIs, is that possible at all?

**Comment by amrbashir** [comment]
This is not possible unfortunately, you have two options:
1. recreate the same effect using HTML/CSS 
2. use multiple small undecorated windows and coordinate their positions (i.e. when one moves, calculate the diff and move the other as well) and emit events to communicate between them.

**Comment by chen-rn** [comment]
Gotcha, Appreciate the quick response!

**Comment by chen-rn** [comment]
@amrbashir Also! As for option 1, I thought it was not possible to apply blur on non DOM elements using CSS? Is there something I'm missing?

**Comment by amrbashir** [comment]
On macos, I think you can have a `backdrop: blur` on the `body` element, but for other platforms, it doesn't work and you may have to recreate a similar effect in HTML/CSS.
