### ISSUE TITLE
corner radius implementation

### ISSUE THREAD

**Issue by svefro** [amrbashir/tauri-plugin-vibrancy#109]
Great crate :)

would be nice if it had option for corner radius on windows also.

I had to implement that on it's own.

````
DwmSetWindowAttribute(
                    handle.hwnd as _,
                    DWMWA_WINDOW_CORNER_PREFERENCE,
                    &DWMWCP_ROUND as *const _ as _,
                    4,
                );
````

**Comment by amrbashir** [comment]
This is not the scope of this crate and the snippet you 'added is enough or you can use `window-shadows` crate which has a similar effect.
