### ISSUE TITLE
Focus change breaks shadow & border on macos sonoma

### ISSUE THREAD

**Issue by RoyalFoxy** [amrbashir/tauri-plugin-vibrancy#112]
I tried the tauri example.

Before focus change
<img width="1800" alt="Screenshot 2023-11-17 at 15 34 23" src="https://github.com/tauri-apps/window-vibrancy/assets/48829979/9e006f5a-ae2b-4a3d-8f0c-c638f131d07d">

After the focus change
<img width="1800" alt="Screenshot 2023-11-17 at 15 34 36" src="https://github.com/tauri-apps/window-vibrancy/assets/48829979/cfbe7ac6-f575-4fd2-ba22-522782ab0c59">

The visual difference is not that big but it seems like the border & shadow is now around a much smaller box in one corner of the window.

**Comment by RoyalFoxy** [comment]
Can be closed as I noticed that this also appears to happen without window-vibrancy. It happens when transparent is set to true in the tauri config so I will reopen the issue on the tauri github

**Comment by ayangweb** [comment]
Hey 👋, have you solved this problem? If you solved it, can you share the solution idea?

**Comment by RoyalFoxy** [comment]
@ayangweb As I said I reopened the issue on [Tauris github](https://github.com/tauri-apps/tauri/issues/8255)
It hasn't been solved in 1.0 but may be solved in 2.0

**Comment by ayangweb** [comment]
> @ayangweb As I said I reopened the issue on [Tauris github](https://github.com/tauri-apps/tauri/issues/8255) It hasn't been solved in 1.0 but may be solved in 2.0

Okay, thanks. I got it.😁
