### ISSUE TITLE
Blur Effects Causing White Background 

### ISSUE THREAD

**Issue by vednig** [amrbashir/tauri-plugin-vibrancy#115]
`apply_mica` and `apply_blur` is causing white background in window.
Here is screenshot with `apply_mica` effect
![image](https://github.com/tauri-apps/window-vibrancy/assets/64083352/0f31c1e2-c348-4040-b441-c905812a9e6e)
Here is screenshot without apply_mica effect
![image](https://github.com/tauri-apps/window-vibrancy/assets/64083352/20f30a1d-e4d6-4011-9fa3-7ac4419ebd05)
In transparency is set to true in both conditions
Window decorations is set to false

**Comment by amrbashir** [comment]
I believe you're using a newer version of Windows 11 and `apply_blur` works only on version 22H1

**Comment by vednig** [comment]
Yes, working on 22H2. Why is it not supported any specific reason?

**Comment by amrbashir** [comment]
The OS itself doesn't support it anymore.
