### ISSUE TITLE
Mica or tabbed can only take effect on one screen

### ISSUE THREAD

**Issue by AuTa** [amrbashir/tauri-plugin-vibrancy#119]
When I moved the window to the second screen, the semi transparent area became opaque. If displayed across screens, it would look like it is now.

![da3a8fae52669750dba33356727086a](https://github.com/tauri-apps/window-vibrancy/assets/1551768/bf067673-5760-403a-8b51-2f864faddb9f)

However, the mica effect of Windows settings and terminals is displayed normally on both screens.

I found a post, but there seems to be no solution.
https://www.reddit.com/r/Windows11/comments/olcecw/mica_material_does_not_work_on_second_monitor/

**Comment by AuTa** [comment]
[fix(core): clear window surface for transparent windows](https://github.com/tauri-apps/tauri/pull/8633)

I discovered this bug fix and tried resizing the window. The new interface appears semi transparent, while the historical interface remains opaque. It should be the same problem.

**Comment by amrbashir** [comment]
This is something we don't control, we are simply calling the windows win32 API to set the backdrop type see https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmsetwindowattribute and https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwm_systembackdrop_type

**Comment by AuTa** [comment]
Maybe my question about windows was misleading. 
This is a transparent bug, hope your last week work will be released, then everything should be fine.

I cloned tauri for local testing and it works fine!
