### ISSUE TITLE
Get Syntax Error: expected BANG from readme's example code

### ISSUE THREAD

**Issue by so2liu** [amrbashir/tauri-plugin-vibrancy#126]
Still don't understand how to use this.

I get Syntax Error: expected BANG when I install and copy the example code.

I am using tauri 2.0.0-alpha.20

**Comment by amrbashir** [comment]
could you show the full error?

also if you're using tauri v2, you can just set the vibrancy effect in tauri.conf.json under `app > windows > windowEffects` key.

**Comment by so2liu** [comment]
> could you show the full error?
> 
> also if you're using tauri v2, you can just set the vibrancy effect in tauri.conf.json under `app > windows > windowEffects` key.

wow, thanks a lot.
