### ISSUE TITLE
Effect not applied to background on FLTK on Windows

### ISSUE THREAD

**Issue by NoelJacob** [amrbashir/tauri-plugin-vibrancy#128]
Earlier it worked perfectly in FLTK - https://github.com/fltk-rs/fltk-rs/discussions/1324#discussioncomment-4306964. Now the effect only applies on Title bar.

With background color:
![GetImage2](https://github.com/tauri-apps/window-vibrancy/assets/54862022/7edcded9-0b75-4a5a-863f-fe46b239c313)  

Without background color:
![GetImage](https://github.com/tauri-apps/window-vibrancy/assets/54862022/22d2b3d6-5a16-45b6-ac18-857e21129976)

**Comment by NoelJacob** [comment]
> I don't know if I should raise issue here or with window-vibrancy. For me it doesn't apply in the background, only at title bar.
> 	Mica 	Blur 	Acrylic
> With background color 	![Screenshot-7](https://camo.githubusercontent.com/78a522ad6502adf188035ccf3464b79925edca638db4b17d8c6041da3fa4cc4e/68747470733a2f2f692e6962622e636f2f706a4d63786e622f53637265656e73686f742d372e706e67) 	![Screenshot-6](https://camo.githubusercontent.com/26c3b754217d54d64da98c138188ccb49d0bf74fb97318cb21b6edb71ad2c4e1/68747470733a2f2f692e6962622e636f2f377459683443722f53637265656e73686f742d362e706e67) 	![Screenshot-5](https://camo.githubusercontent.com/e921149e0cc844d4a1fd780cd6f7c9ac758337577e6eca5fa4604a466de3eae8/68747470733a2f2f692e6962622e636f2f484b7831374b532f53637265656e73686f742d352e706e67)
> No background color 	![Screenshot-2](https://camo.githubusercontent.com/84f0421022139b412ba38d5ae430d0d54cf4b9df946c4faa9eb7def8697e213f/68747470733a2f2f692e6962622e636f2f3962776a6339382f53637265656e73686f742d322e706e67) 	![Screenshot-3](https://camo.githubusercontent.com/0d228a2245f21889fe612165792e330dfcd9d1bcf7c7f83e4744ab942a422a40/68747470733a2f2f692e6962622e636f2f367952317034782f53637265656e73686f742d332e706e67) 	![Screenshot-4](https://camo.githubusercontent.com/58dee716e66a4ebfafeaf2363dc269747b9cd2669131983c60796aec16cd4e39/68747470733a2f2f692e6962622e636f2f6d307337356a5a2f53637265656e73686f742d342e706e67)
> 	Mica/Blur/Acrylic
> Without background color and border 	![Screenshot-8](https://camo.githubusercontent.com/f67c85538a6fadc69504f170e10404d381a46ceb8b3094c0da99bf1f186bcd91/68747470733a2f2f692e6962622e636f2f584a6b5a62386b2f53637265656e73686f742d382e706e67)


Please see this issue - https://github.com/fltk-rs/fltk-rs/issues/1531

**Comment by amrbashir** [comment]
This seems like an issue in fltk, make sure you can create a fully transparent window using fltk then add the window-vibrancy effect.
