### ISSUE TITLE
The trait bound `Window: raw_window_handle::borrowed::HasWindowHandle` is not satisfied

### ISSUE THREAD

**Issue by vaibhav-OP** [amrbashir/tauri-plugin-vibrancy#129]
This is my `main.rs` file 
![image](https://github.com/tauri-apps/window-vibrancy/assets/46072323/cc9a8938-b104-4db6-95b1-d5ca0d0c84a1)
 
 and this is the error it is producing  
![image](https://github.com/tauri-apps/window-vibrancy/assets/46072323/16984ede-9c49-4adf-ad2a-a32cf703a0b4)

I tried following the #55 and downgraded to v0.1.3 and it did not worked either (same error), im using nextjs v13 with tauri v1.6.1

**Comment by amrbashir** [comment]
use `0.4` of this crate not `0.5` as mentioned in the README.
