### ISSUE TITLE
Acrylic effect not working if app is not focused

### ISSUE THREAD

**Issue by FutureExcited** [amrbashir/tauri-plugin-vibrancy#139]
Hey, so I noticed that in Windows 11 the acrylic effect stops working the moment the app is not focused. And it looks really bad this way. The moment I click on the app, it works again.

Here's the effect when app is not focused:
![image](https://github.com/tauri-apps/window-vibrancy/assets/113827671/ea0b9c3d-8434-461b-a7f7-8e5dace9f5ce)

And here's the effect when app is:
![image](https://github.com/tauri-apps/window-vibrancy/assets/113827671/1e6baae1-3e01-4976-8872-088c396fece0)

My build:
Tauri v 1.6.2
Windows 11 23H2

**Comment by Maxanox** [comment]
At the first realese of Arc browser on windows, it has the same behavior when using acrylic UI. Now they removed the acrylic effect. So I think that the problem is from windows itself.

**Comment by amrbashir** [comment]
That's correct, Mica or Acrylic on Windows 11 will be disabled when the window doesn't have focus
