### ISSUE TITLE
`apply_mica` not working on Windows 11

### ISSUE THREAD

**Issue by suptejas** [amrbashir/tauri-plugin-vibrancy#141]
```rs
tauri::Builder::default()
        .setup(|app| {
            let primary = app.get_window("primary").unwrap();

            #[cfg(target_os = "macos")]
            {
                apply_vibrancy(&primary, NSVisualEffectMaterial::HudWindow, None, None)
                    .expect("Unsupported platform! 'apply_vibrancy' is only supported on macOS");
            }

            #[cfg(target_os = "windows")]
            {
                let version = windows_version::OsVersion::current();

                if version.major > 10 || (version.major == 10 && version.build >= 22000) {
                    // This is Windows 11 or newer
                    apply_mica(&primary, None).expect("Failed to apply mica effect");
                } else if version.major == 10 {
                    // This is Windows 10
                    apply_acrylic(&primary, None).expect("Failed to apply blur effect");
                } else {
                    apply_blur(&primary, None).expect("Failed to apply blur effect");
                }
            }

            primary.show().unwrap();
    })
```

window-vibrancy version: 0.4.3, tauri version 1.7.1

i've attached 3 images. 

the first one is with mica applied (as you can see there's no transparency at all. it's just a white background)

the second one is without any effects. this confirms that the transparency on my tauri.conf.json is working as expected. third is with the acrylic effect, which is working as expected.

i'd appreciate your help with this :)

![image](https://github.com/user-attachments/assets/d8fe1668-d14a-41cf-86ae-06fb49732983)
![image](https://github.com/user-attachments/assets/92aa3e35-13dc-4a7e-8255-6b725ca165e0)
![image](https://github.com/user-attachments/assets/d6d6c55e-c553-4d3c-a522-dc8b2a239894)

note: i do not get any errors in the console when trying to apply the effect.

**Comment by CakeAL** [comment]
try to resize the window, I have no idea with it.
I think that's a tauri's bug, when set `"transparent": true`, the background with the initial size will be white. And manually resize the window, the redraw part of the window will be work.

**Comment by suptejas** [comment]
tried to resize. unfortunately i get the same result as above. a pure white background

**Comment by amrbashir** [comment]
what's your windows version reported by `winver` command?

**Comment by suptejas** [comment]
![image](https://github.com/user-attachments/assets/80c3140b-b53d-4a2b-9c69-550dd6bee8f5)

**Comment by CakeAL** [comment]
see this https://github.com/tauri-apps/tauri/issues/10318#issuecomment-2247350656

**Comment by suptejas** [comment]
thanks for the pointer - in my case i actually want decorations to be false all the time, so re-enabling decorations via JS won't fix my issue. cc @amrbashir any ideas here?

**Comment by suptejas** [comment]
by the way, i'm not facing the issue that's mentioned in the bug - the window is fully transparent for me when i set transparent: true without the need for resizing or anything else (see the second image on my first post)

**Comment by amrbashir** [comment]
just tested on Windows 11 23H2 and it works fine

**Comment by suptejas** [comment]
do you mind sharing a link to a repository that confirmed it was working as expected? that'll be helpful to see if the problem persists for me (I'm on a clean windows install too) or is rather caused due to incorrect use

**Comment by amrbashir** [comment]
just:
1. create a new project using `pnpm create tauri`
2. add `window-vibrancy = "0.4.3"` in `src-tauri/Cargo.toml`
3. modify `main.rs` to include
	```rs
	.setup(|app| {
        let main = app.get_window("main").unwrap();
		window_vibrancy::apply_mica(&main, None).expect("Failed to apply mica effect");
		Ok(())
    })
	```
4. modify your frontend CSS, to include 
	```css
	html, body, * {
	  background-color: transparent;
	}
	```
