### ISSUE TITLE
Rounded Corners for Acrylic (windows, tauri v1)

### ISSUE THREAD

**Issue by rawru** [amrbashir/tauri-plugin-vibrancy#142]
### Hi!

**Windows 11 23H2, Tauri v1, window-vibrancy v0.4.3**

The app that I'm creating requires **frameless** windows. And as one might imagine, _harsh, sharp, and squared corners hurts to look at_ (for me, at least).

### Rounded Corners
I've seen **a post about someone having a similar issue** (previously/currently using this same plugin) and **going for a more complicated solution**. I'm quite new to Tauri and Rust, so going that route might not be an option. Here's the link to said post: [how to make tauri app window have rounded corners with window vibrancy](https://stackoverflow.com/questions/77896185/how-to-make-tauri-app-window-have-rounded-corners-with-window-vibrancy)

### Stopping Reversal of Effect
It seems that, when using multiple windows, the acrylic effect fades to a plain grayish color. This color does not change when I change the RGBA value as seen in Some() below:
```rs
#[cfg(target_os = "windows")]
apply_acrylic(&window, Some((255, 255, 255, 128)))
    .expect("Unsupported platform! 'apply_acrylic' is only supported on Windows");
```
The image below 'w/ Acrylic - inactive (shows RGBA)' is what it looks like. This occurs when the user focuses out/blurs from the window. So, clicking on another window or the background will lead to this effect. This doesn't really look that good for my tastes, so I'd like to be able to stop them from happening.

If ever helpful, here are some screenshots of the app =>
**w/ Acrylic - active:**
![Acrylic - active](https://github.com/user-attachments/assets/75094a95-e5c5-4360-b73a-552a4607babe)

**w/ Acrylic - inactive (shows RGBA):**
![Acrylic - inactive](https://github.com/user-attachments/assets/17d1dab6-9ca5-4c90-bb7d-3946ec27c3de)

**w/out Acrylic - just plain old bg-color:rgba and border-radius:**
![No acrylic - plain bg-color:rgba](https://github.com/user-attachments/assets/4730f35b-f96b-4e38-9eab-6b0f866c4e2f)

### Thank you, have a great day!

**Comment by rawru** [comment]
update!

reading through the closed issues... some answers my questions. particularly, the rounded corners.

this has led me to use window-shadows but it seems to remove the acrylic effect when used...

**Comment by amrbashir** [comment]
in order to get the rounded, you need to use `window-shadows` to bring back the shadow and rounded decorations.

**Comment by x93008** [comment]
> update!  更新！
> 
> reading through the closed issues... some answers my questions. particularly, the rounded corners.翻阅已解决的问题……有些问题得到了解答，特别是关于圆角的问题。
> 
> this has led me to use window-shadows but it seems to remove the acrylic effect when used...这导致我尝试使用窗口阴影，但似乎使用后会消除亚克力效果……

How did you solve it
