### ISSUE TITLE
Change Color On Focus Lost (apply_acrylic)

### ISSUE THREAD

**Issue by KingCh1ll** [amrbashir/tauri-plugin-vibrancy#147]
I have the following code:
```
                use window_vibrancy;

                let window = app.get_webview_window("main").unwrap();
                window_vibrancy::apply_acrylic(window, Some((0, 0, 0, 10))).expect("Unsupported platform! 'apply_acrylic' is only supported on Windows 10/11");
```

I do see the acrylic background, however when focus is lost it changes to a gray background. I tried changing the color arg, however this doesn't seem to change anything. I saw someone else ask a similar question, but they weren't using apply_acrylic. This function only takes two args. Is there something I'm missing? Thank you in advance 🙏

**Comment by amrbashir** [comment]
That's how Acrylic material works in Windows, see the Settings app on Windows 10 and how it behaves when the window loses focus.
