### ISSUE TITLE
Acrylic dark on Windows 11 build 22563.1

### ISSUE THREAD

**Issue by decahedron1** [amrbashir/tauri-plugin-vibrancy#17]
This plugin appears to be broken on Windows with Tauri v1.0.0-rc.3. I am testing the example project in this repo, except I updated the Tauri version to 1.0.0-rc.3. The background of the application is fully opaque black (also with some grain effect), even with transparency enabled. The window is transparent when `tauri-plugin-vibrancy` is disabled.

- **Windows version**: Windows 11, build 22563.1
- **WebView2 version**: 98.0.4758.102

**Comment by decahedron1** [comment]
While I was going through my Windows settings to see if somehow the update had screwed with them somehow, I noticed that it had set my wallpaper to black. Setting it back to my wallpaper fixed it (sorry about that 😅); however the blur effects (both `apply_blur` and `apply_acrylic`) are very dark, not sure if that's intended:

![image](https://user-images.githubusercontent.com/61946759/155898216-e88f139e-7254-4c38-9e82-0548477af3fe.png)

**Comment by amrbashir** [comment]
I see you're on Win11 build 22563. I wonder if microsoft changed `SetWindowCompositionAttribute` because it works fine on Win11 build 22000.

**Comment by amrbashir** [comment]
I will close this until the next win11 release. I can't consider win11 22563 for bugs because it is an insider build.
