### ISSUE TITLE
feat: `apply_vibrancy()` for macOS

### ISSUE THREAD

**Issue by amrbashir** [amrbashir/tauri-plugin-vibrancy#2]

**Comment by youngsing** [comment]
If anybody need this feature on macOS, maybe you can take a look at this [fork](https://github.com/youngsing/tauri-plugin-vibrancy).
The code is very simple, according to my needs.

Tested on macOS 12.1 and x86 chips.
![Screen Shot 2021-12-22 at 15 01 01](https://user-images.githubusercontent.com/2562374/147140720-1718cf5f-cada-45ea-8252-8d64abb7103b.png)
![Screen Shot 2021-12-23 at 02 18 44](https://user-images.githubusercontent.com/2562374/147140744-80fe1ce4-6aa1-4d9c-a1e9-e64ae55cbf03.png)

**Comment by amrbashir** [comment]
OMG that is amazing. I sure would like to see a PR.
