### ISSUE TITLE
Get round corners on MacOS

### ISSUE THREAD

**Issue by CafuChino** [amrbashir/tauri-plugin-vibrancy#25]
Through I successfully got vibrancy window on macOS, a sharp window looks pretty weird on MacOS12.
I had already set "decorations": false to hide the title bar.
However, I still need the round corner.

I have tried setting "border-radius" on <HTML> and it is not working.

May I ask,  how can I get round corners back when using this awesome plugin?

Thanks for your reply.

**Comment by amrbashir** [comment]
`border-radius` won't work because it only affects the webview from Tauri and not the native window. Having rounded corners is out of this plugin scope so It will need to be another plugin. No ETAs though.
