### ISSUE TITLE
Effect not applied on Windows 11 with decoration enable

### ISSUE THREAD

**Issue by zenoxs** [amrbashir/tauri-plugin-vibrancy#40]
Hey first of all thanks for the library, it currently works well for me on macOS but I have some trouble with it on Windows 11.
The vibrancy effect (I tried the blur and the mica) is not applied until the window is resized. Then the effect will only be applied to the resized area.

From what I have tested, it only appears when you enable the window decoration.

I took some screenshots to give you a better idea :
![Capture d’écran 2022-05-21 100642](https://user-images.githubusercontent.com/12350021/169642898-ec0df812-d054-4eff-a75f-ba323902b2f8.png)
![Capture d’écran 2022-05-21 100707](https://user-images.githubusercontent.com/12350021/169642944-e85b7965-449c-4973-9ecd-950e8e19bce1.png)

This should look like this without the weird artifact:
![Capture d’écran 2022-05-21 100732](https://user-images.githubusercontent.com/12350021/169642908-5b91467c-ef7e-4309-afea-a07e70264b84.png)

I didn't create a test repository but it should be easy to reproduce, it can be still reproduced on my project: https://github.com/zenoxs/tauri-appcenter-companion

Thanks!

**Comment by FabianLars** [comment]
upstream issue: https://github.com/tauri-apps/tauri/issues/8632

**Comment by amrbashir** [comment]
This is not an issue with the mica effect of this crate but an issue in the `tao` crate. Wnidow with decorations enabled, can't be initially transparent. see https://github.com/tauri-apps/tauri/issues/8632

edit: looks like the super fast saiyan Fabian beat me to it.

**Comment by zenoxs** [comment]
You guys are way too faster, thank you. I have been looking for that.
For those who are looking for a workaround, it looks like you can set decoration to false and then enable it later in rust when the app is ready, and voilà.

```rust
    window
        .get_window("main")
        .unwrap()
        .set_decorations(true)
        .unwrap();
```
