### ISSUE TITLE
Rounded corners not possible with window-vibrancy

### ISSUE THREAD

**Issue by cnrad** [amrbashir/tauri-plugin-vibrancy#43]
Here, without window-vibrancy, I have a transparent window with decorations off; the background of the html is `rgba(16, 17, 20, 0.25)`. I've added a green border to the `html` content (which uses border-radius), so you can see the rounded corners and how it clips the content so the frame of the window is rounded, which is what I want.

<img width="774" alt="image" src="https://user-images.githubusercontent.com/83192247/172057890-48dc67d3-0a88-4f58-83cf-7456174d3a82.png">

Here, with window-vibrancy, you can see that the window content actually goes past the rounded corners.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/83192247/172057961-9fd0d72b-fbfd-45b5-a648-909de4f02647.png">

**Is there a way to disable this, or have it clip to the rounded corners defined in the webview?** This crate essentially does exactly what I want for the background, but I also need rounded corners for my app as well. Hopefully there's an easy way to do this.

cc @amrbashir

**Comment by amrbashir** [comment]
As I explained in https://github.com/tauri-apps/window-vibrancy/pull/26#issuecomment-1064885447 , this is out of the scope of this plugin.

Here is what you need to do though (using tauri):
- If you want rounded corners on Windows 11, you need to use `window-shadows` plugin and enable shadows. I don't know of any other way for rounded corners on any version of Windows at the moment.

- If you want rounded corners on macOS, you need to call native platform APIs, take #26 as an inspiration on how to do it.

**Comment by ptcampbell** [comment]
I wonder if this position could be reconsidered? Looked at one way, this plugin introduces straight corners which don't align to the platform. I can't see any macOS apps that do not have rounded corners.

**Comment by amrbashir** [comment]
Seems like there is no way around it so I agree, I will reopen the issue/PR
