### ISSUE TITLE
Windows 11 22H2 - Non-working Acrylic effect, Laggy Blur effect 

### ISSUE THREAD

**Issue by brys0** [amrbashir/tauri-plugin-vibrancy#45]
It appears on my version of windows 11 seen below has the acrylic effect inoperable and the blur effect lagging the whole PC.
![windows_ver](https://user-images.githubusercontent.com/35676267/173886362-590fb4ea-c1f1-4780-96c1-aabe4790add3.png)

Here is an example with effects being applied:

https://user-images.githubusercontent.com/35676267/173886468-b113494b-5bd5-45f4-8b40-c334f27bdfb9.mp4

**Comment by amrbashir** [comment]
I see that you're using an insider build of Windows 11. I don't know if microsoft broke the api for blur and acrylic. This will have to wait until it is officially released.

**Comment by brys0** [comment]
Thank you for the timely response. This is unrelated but it appears Microsoft is also creating a new effect called tabbed? If/when this will be implemented on the desktop side I'd love to see it in here as well.

https://mspoweruser.com/microsoft-is-working-on-a-new-blur-effect-for-windows-11/

**Comment by amrbashir** [comment]
I am aware of that, and I will include it once it is officially out.

Edit: actually we have the code for that effect ready, it is just no exposed. I will check later if it works on windows 11 22H1

Edit2: it has the same effect as acrylic on 22H1, will wait for 22H2.

**Comment by mxcop** [comment]
I've done a little research into this acrylic lag issue, and it seems Electron had the same issue.
And they managed to solve it by reducing the polling rate to the refresh rate of the monitor.

_(Here is a link to the issue where this was discussed)_
https://github.com/Seo-Rii/electron-acrylic-window/issues/6

Sadly I have no idea how to do this for a Tauri app. 
Nevertheless I thought it might help someone else solve this issue. 😅

**Comment by amrbashir** [comment]
@mxcop this issue is about an insider version of Win 11, and related to acrylic not working at all and laggy blur effect.

If you want please open another issue for the laggy acrylic effect.

**Comment by nodgear** [comment]
Bump:: Window 22H2 is out and being pushed.
This issue persists for now.

Mica effect is working fine.
Blur effect isn't working at all, but lags a lot.
Acrylic doesn't work at all either.


For reference: [Mica for everyone](https://github.com/MicaForEveryone/MicaForEveryone) is able to apply blur without making win32 apps "laggy",  but i understand that this issue is related to mouse pooling rate and should be addressed by Microsoft, not us/

**Comment by kittuov** [comment]
I was able to fix the Acrylic not working issue on Windows 22H2 issue. checkout my pull request #69
