### ISSUE TITLE
the trait `raw_window_handle::HasRawWindowHandle` is not implemented for `Window`

### ISSUE THREAD

**Issue by yn36** [amrbashir/tauri-plugin-vibrancy#57]
![image](https://user-images.githubusercontent.com/52002011/184834500-5bd77a06-15d1-4950-a469-f8ea5636d174.png)

**Comment by FabianLars** [comment]
See #55 and #56.
You need to downgrade window-vibrancy to 0.1.3 until Tauri's next release.
