### ISSUE TITLE
Keep the inactive window vibrancy on macOS

### ISSUE THREAD

**Issue by aizcutei** [amrbashir/tauri-plugin-vibrancy#59]
I hope to make a program can keep vibrancy style even when it is inactive. I find there is a `NSVisualEffectState` enum can control it, but seems it is fixed in this repository (/src/macos.rs line 105): 
```
blurred_view.setState_(NSVisualEffectState::FollowsWindowActiveState);
```

Is there any plan to expose it like `appearance: NSVisualEffectMaterial` as a changeable parameter?

**Comment by amrbashir** [comment]
sure, a PR for it is welcomed because I don't have access to mac (probably will never)
