### ISSUE TITLE
Apply_blur() on windows 10 

### ISSUE THREAD

**Issue by mgrabka** [amrbashir/tauri-plugin-vibrancy#71]
https://user-images.githubusercontent.com/116151164/198380692-b0f484cb-111b-499f-ba96-ffb7df161a38.mov

I think the video speaks for itself, but I'm happy to provide further context if needed.

Windows 10

**Comment by FabianLars** [comment]
Duplicate of https://github.com/tauri-apps/window-vibrancy/issues/40 (upstream issue: https://github.com/tauri-apps/tauri/issues/8632)

**Comment by amrbashir** [comment]
did you enable transparency?
