### ISSUE TITLE
tauri example doesn't work

### ISSUE THREAD

**Issue by Tnze** [amrbashir/tauri-plugin-vibrancy#73]
![image](https://user-images.githubusercontent.com/19628575/202625974-6b07591a-e516-4d30-846e-f1aabc09cd58.png)

**Comment by Tnze** [comment]
`tao` and `winit` doesn't work either.

**Comment by amrbashir** [comment]
Looks like the API used for `blur` is broken on Windows 11 22H2, nothing we can do to fix it. use another effect, acrylic or mica.
