### ISSUE TITLE
No effect on Windows 11

### ISSUE THREAD

**Issue by andrejohansson** [amrbashir/tauri-plugin-vibrancy#85]
When I try to build the example on windows, this is the result for me, am I missing something?

![image](https://user-images.githubusercontent.com/2828428/235303784-db6a9f08-7fa1-4ba1-8804-27ca5dddea32.png)

```
Edition	Windows 11 Pro for Workstations
Version	22H2
Installed on	‎2022-‎09-‎22
OS build	22621.1635
Experience	Windows Feature Experience Pack 1000.22641.1000.0

```

```
❯ cargo --version     
cargo 1.69.0 (6e9a83356 2023-04-12)

window-vibrancy/examples/tauri on  dev [!?] is  v1.0.0 via  v16.18.0 on  (eu-north-1) 
❯ rustc --version
rustc 1.69.0 (84c898d65 2023-04-16)
```

**Comment by amrbashir** [comment]
The example is using `apply_blur` which doesn't work on recent windows 11 versions, you need to use another effect, please see https://github.com/tauri-apps/window-vibrancy/tree/dev#available-functions for more information

**Comment by andrejohansson** [comment]
ok, I missed the 22H1 only notation. Thanks for a quick response.
