### ISSUE TITLE
Using the apply_vibrancy on macOS on focus change window is no longer transparent

### ISSUE THREAD

**Issue by MadsFrost** [amrbashir/tauri-plugin-vibrancy#88]
Hi, how do I fix the apply_vibrancy on "non-focused" the window goes back to not being transparent?

"apply_vibrancy(&window, NSVisualEffectMaterial::HudWindow, None, None)"

Examples attached:
Non-focused:
<img width="939" alt="Screenshot 2023-06-01 at 14 34 15" src="https://github.com/tauri-apps/window-vibrancy/assets/20844344/193f766d-dadd-40d1-81bf-d6a36958a4c5">

Focused:
<img width="939" alt="Screenshot 2023-06-01 at 14 34 43" src="https://github.com/tauri-apps/window-vibrancy/assets/20844344/a8417386-b4ba-4e0e-9e72-cda0a704fe34">

**Comment by FabianLars** [comment]
You have to provide a "[state](https://docs.rs/window-vibrancy/0.3.2/window_vibrancy/enum.NSVisualEffectState.html)" arg in the [apply_vibrancy](https://docs.rs/window-vibrancy/0.3.2/window_vibrancy/fn.apply_vibrancy.html) function.
Something like this
```rs
apply_vibrancy(&window, NSVisualEffectMaterial::HudWindow, Some(NSVisualEffectState::Active), None);
```

**Comment by MadsFrost** [comment]
> You have to provide a "[state](https://docs.rs/window-vibrancy/0.3.2/window_vibrancy/enum.NSVisualEffectState.html)" arg in the [apply_vibrancy](https://docs.rs/window-vibrancy/0.3.2/window_vibrancy/fn.apply_vibrancy.html) function. Something like this
> 
> ```rust
> apply_vibrancy(&window, NSVisualEffectMaterial::HudWindow, Some(NSVisualEffectState::Active), None);
> ```

Ah thank you @FabianLars
