### ISSUE TITLE
Doesn't work on Windows 22H2

### ISSUE THREAD

**Issue by NiiightmareXD** [amrbashir/tauri-plugin-vibrancy#95]
https://github.com/tauri-apps/window-vibrancy/assets/90005793/f405bcf4-f5df-4e5f-be44-29b5817ab0f9

**Comment by amrbashir** [comment]
It does work but there is a bug that prevents the window surface from being transparent on the get-go so you need to disable shadows when creating the window and then enable them back again. I have pushed a commit to fix this, try again please.

**Comment by colorpeach** [comment]
@amrbashir I am using version v0.5.0 and it still has no effect on Windows 22H2.
