### ISSUE TITLE
how to create rounded arrow 

### ISSUE THREAD

**Issue by reslear** [amrbashir/tauri-plugin-vibrancy#98]
<img width="445" alt="Screenshot 2023-08-14 at 15 03 17" src="https://github.com/tauri-apps/window-vibrancy/assets/12596485/b27a4b78-6d63-4ce0-8c52-a74571efc927">

my app:
<img width="422" alt="Screenshot 2023-08-14 at 15 04 30" src="https://github.com/tauri-apps/window-vibrancy/assets/12596485/907f42ea-45d6-4013-8ebd-8ad6199dc54f">

**Comment by amrbashir** [comment]
for that, you would need to use `objc` crate to manipulate the window shape directly, maybe even fork this crate and modify it but it is beyond the scope of this crate.
