### ISSUE TITLE
[Feature Request] Having an option to round corners

### ISSUE THREAD

**Issue by Wolfaredumb** [amrbashir/tauri-plugin-vibrancy#99]
### Scenario Reproduction

1. Create a Tauri Project
2. Make window transparent
3. Apply a backdrop and round its corner using border-radius in CSS
4. Use Window Vibrancy's Tauri example on Github

### Feature Request
Ability to round corners as currently the backdrop has rounded corners but the Window Vibrancy's window corners are sharp and visible.

### Am I able to do this myself
Currently I'm a Rust beginner and don't have enough skill to add this feature. Thus this request is a humble plea to add this feature.

**Comment by amrbashir** [comment]
There is already a 3rd parameter for radius in `apply_vibrancy` function for macOS. For windows, there is no way to set a custom radius, however if you're on Windows 11, and have a Window without decorations and want to have rounded corners, you can opt-into enabling back some decorations (without the titlebar) by using [`window-shadows`](https://github.com/tauri-apps/window-shadows) crate
